### ISSUE TITLE
sorry for posting here

### ISSUE THREAD

**Issue by ahmedfamhy3** [drygdryg/ds-password-changer#4]
well i'm sorry for posting this here tho it's not relaited but i would be grateful if allowed issues on your **RTL8192EU** fork
please add support for kernel 6 or how i can fix this issue
![-2147483648_-210088](https://user-images.githubusercontent.com/122128503/211109878-092089a4-cd6d-4bdf-8348-e0d971694812.jpg)

**Comment by drygdryg** [comment]
Check https://github.com/clnhub/rtl8192eu-linux
